services:
  neo4j:
    image: neo4j:2025.04.0
    container_name: neo4jsentrix
    env_file:
      - ./mcp-server/.env
    ports:
      - "7474:7474" #http browser
      - "7687:7687" #bolt
    volumes:
      - neo4j_data:/data # this is named volume docker manages the stored data loc on host  for host bind mount and custom managed loc for neo4j data in the host machine use ./neo4j_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrantjsentrix
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API & Web UI
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage # host bind
    deploy:
      resources:
        limits:
          memory: 1G  # Qdrant limited to 1GB RAM
  postgres:
    image: postgres:16
    container_name: postgresjsentrix
    env_file:
      - ./gateway/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
volumes: # 🎈 remove this in case host bind mount supplied under services-neo4j-volumes section above
  neo4j_data:
  pg_data:
